from enum import StrEnum


class Language(StrEnum):
    RU = "ru"
    EN = "en"
    UK = "uk"
    TR = "tr"


_EN = {
    "choose_language": "Choose language",
    "welcome": "Telegram Stars and Premium",
    "welcome_lead": "Choose a gift. The bot checks the recipient before payment.",
    "buy_stars": "Buy Stars",
    "buy_premium": "Buy Premium",
    "my_orders": "My orders",
    "language": "Language",
    "api": "API for your shop",
    "choose_amount": "Choose the Stars amount or enter your own (50–1,000,000).",
    "choose_duration": "Choose Premium duration.",
    "custom_amount": "Custom amount",
    "invalid_amount": "Enter a whole number from 50 to 1,000,000.",
    "choose_recipient": "Who should receive the purchase?",
    "for_me": "For me",
    "enter_username": "Enter the recipient username, for example @username.",
    "invalid_username": "Invalid Telegram username.",
    "recipient_ok": "Recipient: {username}",
    "choose_asset": "Choose payment currency.",
    "usdt_unavailable_title": "USDT is temporarily unavailable",
    "usdt_unavailable": "The store wallet needs more GRAM for network fees. Choose GRAM or try USDT later.",
    "unavailable": "Purchase is unavailable for this recipient: {message}",
    "service_error": "The service is temporarily unavailable. Try again later.",
    "confirm": "Product: {product}\nRecipient: {username}\nPayment: {price} {asset}\n\nConfirm the order?",
    "confirm_title": "Confirm order",
    "confirm_lead": "Check the recipient and final price before creating the invoice.",
    "product_label": "Product",
    "recipient_label": "Recipient",
    "payment_label": "Payment",
    "confirm_button": "Create invoice",
    "cancel": "Cancel",
    "invoice": "Invoice #{order_id}\nSend exactly <b>{price} {asset}</b> to:\n<code>{address}</code>\nComment: <code>{reference}</code>\nThe invoice is valid for 15 minutes.",
    "invoice_title": "Invoice #{order_id}",
    "invoice_lead": "Send the exact amount with the exact comment.",
    "invoice_details": "Address: {address}\nComment: {reference}",
    "expires_label": "Valid for",
    "expires_value": "15 minutes",
    "copy_order": "Copy order ID",
    "open_wallet": "Open wallet",
    "copy_address": "Copy address",
    "copy_reference": "Copy comment",
    "check_payment": "Check payment",
    "payment_waiting": "Payment has not been found yet. Check the exact amount and comment.",
    "payment_found": "Payment received. The purchase is being processed.",
    "completed": "Order #{order_id} completed.\nTransaction: <code>{tx_hash}</code>",
    "completed_title": "Order #{order_id} completed",
    "completed_lead": "The purchase was delivered successfully.",
    "order_label": "Order",
    "transaction_label": "Transaction",
    "fragment_label": "Fragment purchase",
    "copy_transaction": "Copy transaction",
    "copy_purchase": "Copy purchase ID",
    "failed": "Order #{order_id} could not be completed. The owner has been notified.",
    "manual_review": "Order #{order_id} requires manual review. The owner has been notified.",
    "expired": "Invoice #{order_id} has expired. A late payment is handled manually.",
    "order_line": "#{order_id} — {product} — {state}",
    "state_draft": "draft",
    "state_awaiting_payment": "awaiting payment",
    "state_paid": "paid",
    "state_purchasing": "processing",
    "state_completed": "completed",
    "state_failed": "failed",
    "state_reconciliation_required": "reconciliation required",
    "state_manual_review": "manual review",
    "state_expired": "expired",
    "no_orders": "You have no orders yet.",
    "back": "Back",
    "api_promo": "Want your own shop? Fragment Market API:\nhttps://stars-market.duckdns.org/api\nSource: https://github.com/slightbasebo/fragment-api-dev",
    "stars": "{amount} Stars",
    "premium": "Premium for {amount} months",
}


def _translated(**changes: str) -> dict[str, str]:
    return _EN | changes


TEXTS = {
    Language.EN: _EN,
    Language.RU: _translated(
        choose_language="Выберите язык", welcome="Telegram Stars и Premium",
        welcome_lead="Выберите подарок. Получателя бот проверит до оплаты.",
        buy_stars="Купить звезды", buy_premium="Купить Premium", my_orders="Мои заказы",
        language="Язык", api="API для своего магазина",
        choose_amount="Выберите количество звезд или введите свое (50–1 000 000).",
        choose_duration="Выберите срок Premium.", custom_amount="Свое количество",
        invalid_amount="Введите целое число от 50 до 1 000 000.",
        choose_recipient="Кому отправить покупку?", for_me="Мне",
        enter_username="Введите username получателя, например @username.",
        invalid_username="Некорректный Telegram username.", recipient_ok="Получатель: {username}",
        choose_asset="Выберите валюту оплаты.",
        usdt_unavailable_title="USDT временно недоступен",
        usdt_unavailable="Кошельку магазина не хватает GRAM на сетевую комиссию. Выберите GRAM или попробуйте USDT позже.",
        unavailable="Покупка недоступна для этого получателя: {message}",
        service_error="Сервис временно недоступен. Попробуйте позже.",
        confirm="Товар: {product}\nПолучатель: {username}\nК оплате: {price} {asset}\n\nПодтвердить заказ?",
        confirm_title="Подтверждение заказа",
        confirm_lead="Проверьте получателя и итоговую цену перед созданием счёта.",
        product_label="Товар", recipient_label="Получатель", payment_label="К оплате",
        confirm_button="Создать счет", cancel="Отмена",
        invoice="Счет #{order_id}\nОтправьте ровно <b>{price} {asset}</b> на адрес:\n<code>{address}</code>\nКомментарий: <code>{reference}</code>\nСчет действует 15 минут.",
        invoice_title="Счёт #{order_id}",
        invoice_lead="Отправьте точную сумму и обязательно укажите комментарий.",
        invoice_details="Адрес: {address}\nКомментарий: {reference}",
        expires_label="Действует", expires_value="15 минут", copy_order="Копировать № заказа",
        open_wallet="Открыть кошелек", copy_address="Скопировать адрес",
        copy_reference="Скопировать комментарий", check_payment="Проверить оплату",
        payment_waiting="Оплата пока не найдена. Проверьте точную сумму и комментарий.",
        payment_found="Оплата получена. Покупка выполняется.",
        completed="Заказ #{order_id} выполнен.\nТранзакция: <code>{tx_hash}</code>",
        completed_title="Заказ #{order_id} выполнен",
        completed_lead="Покупка успешно доставлена получателю.",
        order_label="Заказ", transaction_label="Транзакция",
        fragment_label="Покупка Fragment", copy_transaction="Копировать транзакцию",
        copy_purchase="Копировать ID покупки",
        failed="Заказ #{order_id} не выполнен. Владелец уведомлен.",
        manual_review="Заказ #{order_id} требует ручной проверки. Владелец уведомлен.",
        expired="Счет #{order_id} истек. Поздний платеж проверяется вручную.",
        order_line="#{order_id} — {product} — {state}", no_orders="У вас пока нет заказов.",
        state_draft="черновик", state_awaiting_payment="ожидает оплату",
        state_paid="оплачен", state_purchasing="выполняется",
        state_completed="выполнен", state_failed="ошибка",
        state_reconciliation_required="нужна сверка",
        state_manual_review="ручная проверка", state_expired="истёк",
        back="Назад", stars="{amount} звезд", premium="Premium на {amount} мес.",
        api_promo="Хотите свой магазин? Fragment Market API:\nhttps://stars-market.duckdns.org/api\nИсходники: https://github.com/slightbasebo/fragment-api-dev",
    ),
    Language.UK: _translated(
        choose_language="Оберіть мову", welcome="Telegram Stars і Premium",
        welcome_lead="Оберіть подарунок. Отримувача бот перевірить до оплати.",
        buy_stars="Купити зірки", buy_premium="Купити Premium", my_orders="Мої замовлення",
        language="Мова", api="API для свого магазину",
        choose_amount="Оберіть кількість зірок або введіть свою (50–1 000 000).",
        choose_duration="Оберіть термін Premium.", custom_amount="Своя кількість",
        invalid_amount="Введіть ціле число від 50 до 1 000 000.",
        choose_recipient="Кому надіслати покупку?", for_me="Мені",
        enter_username="Введіть username отримувача, наприклад @username.",
        invalid_username="Некоректний Telegram username.", recipient_ok="Отримувач: {username}",
        choose_asset="Оберіть валюту оплати.",
        usdt_unavailable_title="USDT тимчасово недоступний",
        usdt_unavailable="Гаманцю магазину бракує GRAM на мережеву комісію. Оберіть GRAM або спробуйте USDT пізніше.",
        unavailable="Покупка недоступна для цього отримувача: {message}",
        service_error="Сервіс тимчасово недоступний. Спробуйте пізніше.",
        confirm="Товар: {product}\nОтримувач: {username}\nДо сплати: {price} {asset}\n\nПідтвердити замовлення?",
        confirm_title="Підтвердження замовлення",
        confirm_lead="Перевірте отримувача та підсумкову ціну перед створенням рахунку.",
        product_label="Товар", recipient_label="Отримувач", payment_label="До сплати",
        confirm_button="Створити рахунок", cancel="Скасувати",
        invoice="Рахунок #{order_id}\nНадішліть рівно <b>{price} {asset}</b> на адресу:\n<code>{address}</code>\nКоментар: <code>{reference}</code>\nРахунок дійсний 15 хвилин.",
        invoice_title="Рахунок #{order_id}",
        invoice_lead="Надішліть точну суму та обов'язково вкажіть коментар.",
        invoice_details="Адреса: {address}\nКоментар: {reference}",
        expires_label="Дійсний", expires_value="15 хвилин", copy_order="Копіювати № замовлення",
        open_wallet="Відкрити гаманець", copy_address="Копіювати адресу",
        copy_reference="Копіювати коментар", check_payment="Перевірити оплату",
        payment_waiting="Оплату ще не знайдено. Перевірте точну суму та коментар.",
        payment_found="Оплату отримано. Покупка виконується.",
        completed="Замовлення #{order_id} виконано.\nТранзакція: <code>{tx_hash}</code>",
        completed_title="Замовлення #{order_id} виконано",
        completed_lead="Покупку успішно доставлено отримувачу.",
        order_label="Замовлення", transaction_label="Транзакція",
        fragment_label="Покупка Fragment", copy_transaction="Копіювати транзакцію",
        copy_purchase="Копіювати ID покупки",
        failed="Замовлення #{order_id} не виконано. Власника повідомлено.",
        manual_review="Замовлення #{order_id} потребує ручної перевірки. Власника повідомлено.",
        expired="Рахунок #{order_id} прострочено. Пізній платіж перевіряється вручну.",
        order_line="#{order_id} — {product} — {state}", no_orders="У вас ще немає замовлень.",
        state_draft="чернетка", state_awaiting_payment="очікує оплату",
        state_paid="оплачено", state_purchasing="виконується",
        state_completed="виконано", state_failed="помилка",
        state_reconciliation_required="потрібна звірка",
        state_manual_review="ручна перевірка", state_expired="прострочено",
        back="Назад", stars="{amount} зірок", premium="Premium на {amount} міс.",
        api_promo="Хочете свій магазин? Fragment Market API:\nhttps://stars-market.duckdns.org/api\nКод: https://github.com/slightbasebo/fragment-api-dev",
    ),
    Language.TR: _translated(
        choose_language="Dil seçin", welcome="Telegram Stars ve Premium",
        welcome_lead="Bir hediye seçin. Bot, ödemeden önce alıcıyı kontrol eder.",
        buy_stars="Stars satın al", buy_premium="Premium satın al", my_orders="Siparişlerim",
        language="Dil", api="Kendi mağazanız için API",
        choose_amount="Stars miktarını seçin veya girin (50–1.000.000).",
        choose_duration="Premium süresini seçin.", custom_amount="Özel miktar",
        invalid_amount="50 ile 1.000.000 arasında bir tam sayı girin.",
        choose_recipient="Satın alma kime gönderilsin?", for_me="Kendim için",
        enter_username="Alıcının kullanıcı adını girin, örneğin @username.",
        invalid_username="Geçersiz Telegram kullanıcı adı.", recipient_ok="Alıcı: {username}",
        choose_asset="Ödeme para birimini seçin.",
        usdt_unavailable_title="USDT geçici olarak kullanılamıyor",
        usdt_unavailable="Mağaza cüzdanında ağ ücreti için yeterli GRAM yok. GRAM seçin veya USDT'yi daha sonra deneyin.",
        unavailable="Bu alıcı için satın alma kullanılamıyor: {message}",
        service_error="Hizmet geçici olarak kullanılamıyor. Daha sonra tekrar deneyin.",
        confirm="Ürün: {product}\nAlıcı: {username}\nÖdeme: {price} {asset}\n\nSiparişi onaylıyor musunuz?",
        confirm_title="Siparişi onayla",
        confirm_lead="Faturayı oluşturmadan önce alıcıyı ve son fiyatı kontrol edin.",
        product_label="Ürün", recipient_label="Alıcı", payment_label="Ödeme",
        confirm_button="Fatura oluştur", cancel="İptal",
        invoice="Fatura #{order_id}\nTam olarak <b>{price} {asset}</b> gönderin:\n<code>{address}</code>\nAçıklama: <code>{reference}</code>\nFatura 15 dakika geçerlidir.",
        invoice_title="Fatura #{order_id}",
        invoice_lead="Tam tutarı gönderin ve açıklamayı eksiksiz yazın.",
        invoice_details="Adres: {address}\nAçıklama: {reference}",
        expires_label="Geçerlilik", expires_value="15 dakika", copy_order="Sipariş no'yu kopyala",
        open_wallet="Cüzdanı aç", copy_address="Adresi kopyala",
        copy_reference="Yorumu kopyala", check_payment="Ödemeyi kontrol et",
        payment_waiting="Ödeme henüz bulunamadı. Tutarı ve yorumu kontrol edin.",
        payment_found="Ödeme alındı. Satın alma işleniyor.",
        completed="Sipariş #{order_id} tamamlandı.\nİşlem: <code>{tx_hash}</code>",
        completed_title="Sipariş #{order_id} tamamlandı",
        completed_lead="Satın alma alıcıya başarıyla teslim edildi.",
        order_label="Sipariş", transaction_label="İşlem",
        fragment_label="Fragment satın alımı", copy_transaction="İşlemi kopyala",
        copy_purchase="Satın alma kimliğini kopyala",
        failed="Sipariş #{order_id} tamamlanamadı. Mağaza sahibi bilgilendirildi.",
        manual_review="Sipariş #{order_id} manuel inceleme gerektiriyor.",
        expired="Fatura #{order_id} süresi doldu. Geç ödeme manuel incelenir.",
        order_line="#{order_id} — {product} — {state}", no_orders="Henüz siparişiniz yok.",
        state_draft="taslak", state_awaiting_payment="ödeme bekleniyor",
        state_paid="ödendi", state_purchasing="işleniyor",
        state_completed="tamamlandı", state_failed="başarısız",
        state_reconciliation_required="mutabakat gerekli",
        state_manual_review="manuel inceleme", state_expired="süresi doldu",
        back="Geri", stars="{amount} Stars", premium="{amount} aylık Premium",
        api_promo="Kendi mağazanızı ister misiniz? Fragment Market API:\nhttps://stars-market.duckdns.org/api\nKaynak: https://github.com/slightbasebo/fragment-api-dev",
    ),
}


def text(language: Language | str, key: str, **values: object) -> str:
    lang = language if isinstance(language, Language) else Language(language)
    return TEXTS[lang][key].format(**values)
